### ISSUE TITLE
nanomsg git tag

### ISSUE THREAD

**Issue by RalfKliemt** [FairRootGroup/alfadist#10]
Ahoi.

When trying to build from scratch, there is a problem with nanomsg. I could track it down to the git clone process, which somehow does not receives all the tags. The subsequent checkout fails and abots the whole process. In the web a 'git fetch --tags' after cloning is proposed. 
However, the git related part of the build script (sw/SPECS/.../nanomsg/v1.1.2-1/build.sh) is automatically generated.

Cheers!
  Ralf

> ==> Building nanomsg@v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + set -e
> DEBUG:FairRoot:nanomsg:523c0534: + set +h
> DEBUG:FairRoot:nanomsg:523c0534: + export WORK_DIR=/data.local1/ALFA/sw
> DEBUG:FairRoot:nanomsg:523c0534: + WORK_DIR=/data.local1/ALFA/sw
> DEBUG:FairRoot:nanomsg:523c0534: + '[' X = X ']'
> DEBUG:FairRoot:nanomsg:523c0534: + source /data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1/etc/profile.d/init.sh
> DEBUG:FairRoot:nanomsg:523c0534: ++ '[' X = X ']'
> DEBUG:FairRoot:nanomsg:523c0534: ++ source /data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/etc/profile.d/init.sh
> DEBUG:FairRoot:nanomsg:523c0534: +++ export DEFAULTS_RELEASE_ROOT=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1
> DEBUG:FairRoot:nanomsg:523c0534: +++ DEFAULTS_RELEASE_ROOT=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1
> DEBUG:FairRoot:nanomsg:523c0534: +++ export DEFAULTS_RELEASE_VERSION=v1
> DEBUG:FairRoot:nanomsg:523c0534: +++ DEFAULTS_RELEASE_VERSION=v1
> DEBUG:FairRoot:nanomsg:523c0534: +++ export DEFAULTS_RELEASE_REVISION=1
> DEBUG:FairRoot:nanomsg:523c0534: +++ DEFAULTS_RELEASE_REVISION=1
> DEBUG:FairRoot:nanomsg:523c0534: +++ export DEFAULTS_RELEASE_HASH=786d8dd4fef86e06cbc956cb612d7819ec5967ad
> DEBUG:FairRoot:nanomsg:523c0534: +++ DEFAULTS_RELEASE_HASH=786d8dd4fef86e06cbc956cb612d7819ec5967ad
> DEBUG:FairRoot:nanomsg:523c0534: +++ export DEFAULTS_RELEASE_COMMIT=0
> DEBUG:FairRoot:nanomsg:523c0534: +++ DEFAULTS_RELEASE_COMMIT=0
> DEBUG:FairRoot:nanomsg:523c0534: +++ export CXX_STANDARD=11
> DEBUG:FairRoot:nanomsg:523c0534: +++ CXX_STANDARD=11
> DEBUG:FairRoot:nanomsg:523c0534: +++ export CXXFLAGS=-fPIC
> DEBUG:FairRoot:nanomsg:523c0534: +++ CXXFLAGS=-fPIC
> DEBUG:FairRoot:nanomsg:523c0534: +++ export CFLAGS=-fPIC
> DEBUG:FairRoot:nanomsg:523c0534: +++ CFLAGS=-fPIC
> DEBUG:FairRoot:nanomsg:523c0534: +++ export CMAKE_BUILD_TYPE=RELWITHDEBINFO
> DEBUG:FairRoot:nanomsg:523c0534: +++ CMAKE_BUILD_TYPE=RELWITHDEBINFO
> DEBUG:FairRoot:nanomsg:523c0534: +++ export DYLD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:
> DEBUG:FairRoot:nanomsg:523c0534: +++ DYLD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:
> DEBUG:FairRoot:nanomsg:523c0534: +++ export PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/bin:/u/kliemt/bin:/u/kliemt/Software/java/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/u/kliemt/bin
> DEBUG:FairRoot:nanomsg:523c0534: +++ PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/bin:/u/kliemt/bin:/u/kliemt/Software/java/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/u/kliemt/bin
> DEBUG:FairRoot:nanomsg:523c0534: +++ export LD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:/u/kliemt/Software/java/lib:
> DEBUG:FairRoot:nanomsg:523c0534: +++ LD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:/u/kliemt/Software/java/lib:
> DEBUG:FairRoot:nanomsg:523c0534: ++ export CMAKE_ROOT=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1
> DEBUG:FairRoot:nanomsg:523c0534: ++ CMAKE_ROOT=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1
> DEBUG:FairRoot:nanomsg:523c0534: ++ export CMAKE_VERSION=v3.11.1
> DEBUG:FairRoot:nanomsg:523c0534: ++ CMAKE_VERSION=v3.11.1
> DEBUG:FairRoot:nanomsg:523c0534: ++ export CMAKE_REVISION=1
> DEBUG:FairRoot:nanomsg:523c0534: ++ CMAKE_REVISION=1
> DEBUG:FairRoot:nanomsg:523c0534: ++ export CMAKE_HASH=c100970f7e341998af33425e054b545d17fc7a1e
> DEBUG:FairRoot:nanomsg:523c0534: ++ CMAKE_HASH=c100970f7e341998af33425e054b545d17fc7a1e
> DEBUG:FairRoot:nanomsg:523c0534: ++ export CMAKE_COMMIT=v3.11.1
> DEBUG:FairRoot:nanomsg:523c0534: ++ CMAKE_COMMIT=v3.11.1
> DEBUG:FairRoot:nanomsg:523c0534: ++ export DYLD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1/lib:/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:
> DEBUG:FairRoot:nanomsg:523c0534: ++ DYLD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1/lib:/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:
> DEBUG:FairRoot:nanomsg:523c0534: ++ export PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1/bin:/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/bin:/u/kliemt/bin:/u/kliemt/Software/java/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/u/kliemt/bin
> DEBUG:FairRoot:nanomsg:523c0534: ++ PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1/bin:/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/bin:/u/kliemt/bin:/u/kliemt/Software/java/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/u/kliemt/bin
> DEBUG:FairRoot:nanomsg:523c0534: ++ export LD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1/lib:/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:/u/kliemt/Software/java/lib:
> DEBUG:FairRoot:nanomsg:523c0534: ++ LD_LIBRARY_PATH=/data.local1/ALFA/sw/ubuntu1404_x86-64/CMake/v3.11.1-1/lib:/data.local1/ALFA/sw/ubuntu1404_x86-64/defaults-release/v1-1/lib:/u/kliemt/Software/java/lib:
> DEBUG:FairRoot:nanomsg:523c0534: + '[' Xv1 = X ']'
> DEBUG:FairRoot:nanomsg:523c0534: + export PKG_NAME=nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + PKG_NAME=nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + export PKG_VERSION=v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + PKG_VERSION=v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + export PKG_BUILDNUM=1
> DEBUG:FairRoot:nanomsg:523c0534: + PKG_BUILDNUM=1
> DEBUG:FairRoot:nanomsg:523c0534: + export SOURCE0=https://github.com/nanomsg/nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + SOURCE0=https://github.com/nanomsg/nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + export PKGPATH=ubuntu1404_x86-64/nanomsg/v1.1.2-1
> DEBUG:FairRoot:nanomsg:523c0534: + PKGPATH=ubuntu1404_x86-64/nanomsg/v1.1.2-1
> DEBUG:FairRoot:nanomsg:523c0534: + mkdir -p /data.local1/ALFA/sw/BUILD /data.local1/ALFA/sw/SOURCES /data.local1/ALFA/sw/TARS /data.local1/ALFA/sw/SPECS /data.local1/ALFA/sw/INSTALLROOT
> DEBUG:FairRoot:nanomsg:523c0534: + export BUILDROOT=/data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00
> DEBUG:FairRoot:nanomsg:523c0534: + BUILDROOT=/data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00
> DEBUG:FairRoot:nanomsg:523c0534: + '[' h == / ']'
> DEBUG:FairRoot:nanomsg:523c0534: + export INSTALLROOT=/data.local1/ALFA/sw/INSTALLROOT/d2d401c61ba25c03860285637ce2ce9b1834bd00/ubuntu1404_x86-64/nanomsg/v1.1.2-1
> DEBUG:FairRoot:nanomsg:523c0534: + INSTALLROOT=/data.local1/ALFA/sw/INSTALLROOT/d2d401c61ba25c03860285637ce2ce9b1834bd00/ubuntu1404_x86-64/nanomsg/v1.1.2-1
> DEBUG:FairRoot:nanomsg:523c0534: + export SOURCEDIR=/data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + SOURCEDIR=/data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + export BUILDDIR=/data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00/nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + BUILDDIR=/data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00/nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + SHORT_TAG=v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: ++ dirname /data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + mkdir -p /data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + [[ v1.1.2 != v1.1.2 ]]
> DEBUG:FairRoot:nanomsg:523c0534: + rm -fr /data.local1/ALFA/sw/INSTALLROOT/d2d401c61ba25c03860285637ce2ce9b1834bd00
> DEBUG:FairRoot:nanomsg:523c0534: + [[ 0 == 0 ]]
> DEBUG:FairRoot:nanomsg:523c0534: + rm -rf /data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00
> DEBUG:FairRoot:nanomsg:523c0534: + mkdir -p /data.local1/ALFA/sw/INSTALLROOT/d2d401c61ba25c03860285637ce2ce9b1834bd00/ubuntu1404_x86-64/nanomsg/v1.1.2-1 /data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00 /data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00/nanomsg /data.local1/ALFA/sw/INSTALLROOT/d2d401c61ba25c03860285637ce2ce9b1834bd00/ubuntu1404_x86-64/nanomsg/v1.1.2-1
> DEBUG:FairRoot:nanomsg:523c0534: + cd /data.local1/ALFA/sw/BUILD/d2d401c61ba25c03860285637ce2ce9b1834bd00
> DEBUG:FairRoot:nanomsg:523c0534: + ln -snf d2d401c61ba25c03860285637ce2ce9b1834bd00 /data.local1/ALFA/sw/BUILD/nanomsg-latest
> DEBUG:FairRoot:nanomsg:523c0534: + [[ -n '' ]]
> DEBUG:FairRoot:nanomsg:523c0534: + export GIT_REFERENCE=/data.local1/ALFA/sw/MIRROR/nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + GIT_REFERENCE=/data.local1/ALFA/sw/MIRROR/nanomsg
> DEBUG:FairRoot:nanomsg:523c0534: + [[ ! https://github.com/nanomsg/nanomsg == '' ]]
> DEBUG:FairRoot:nanomsg:523c0534: + [[ h != \/ ]]
> DEBUG:FairRoot:nanomsg:523c0534: + [[ ! -d /data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2 ]]
> DEBUG:FairRoot:nanomsg:523c0534: + rm -rf /data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + git clone --reference /data.local1/ALFA/sw/MIRROR/nanomsg https://github.com/nanomsg/nanomsg /data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: Cloning into '/data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2'...
> DEBUG:FairRoot:nanomsg:523c0534: + cd /data.local1/ALFA/sw/SOURCES/nanomsg/v1.1.2/v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: + git checkout v1.1.2
> DEBUG:FairRoot:nanomsg:523c0534: error: pathspec 'v1.1.2' did not match any file(s) known to git.
> DEBUG:FairRoot:nanomsg:523c0534:
> ERROR:FairRoot:nanomsg:523c0534: Error while executing /data.local1/ALFA/sw/SPECS/ubuntu1404_x86-64/nanomsg/v1.1.2-1/build.sh on `lxds017'.
> ERROR:FairRoot:nanomsg:523c0534: Log can be found in /data.local1/ALFA/sw/BUILD/nanomsg-latest/log.
> ERROR:FairRoot:nanomsg:523c0534: Please upload it to CERNBox/Dropbox if you intend to request support.
> ERROR:FairRoot:nanomsg:523c0534: Build directory is /data.local1/ALFA/sw/BUILD/nanomsg-latest/nanomsg.
>

**Comment by fuhlig1** [comment]
Hi Ralf,

I think the problem is a wrong tag in the nanomsg recipe. Instead of „v1.1.2" it should be „1.1.2“.
Could you please try if changing the tag in the recipe solves the problem.

Ciao

Florian

**Comment by dennisklein** [comment]
Fixed.
